//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Чистый_ремонт.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Decoration()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int DecorationID { get; set; }
        public string DecorationName { get; set; }
        public double DecorationPriceSqM { get; set; }
        public string DecorationDesc { get; set; }
        public string DecorationImg { get; set; }
        public Nullable<double> DecorationDiscountPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
