//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Чистый_ремонт.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderDecID { get; set; }
        public int OrderClientID { get; set; }
        public int OrderWorkerID { get; set; }
        public int OrderStatusID { get; set; }
        public double OrderSqM { get; set; }
        public double OrderPrice { get; set; }
        public string OrderComm { get; set; }
    
        public virtual Decoration Decoration { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
